# Generated by Django 4.2.3 on 2023-07-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_badprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badprofile",
            old_name="badimage",
            new_name="image",
        ),
    ]
