# Generated by Django 4.2.3 on 2023-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(default="default.jpg", upload_to="resume_files"),
        ),
    ]
