# Generated by Django 4.2.3 on 2023-07-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_alter_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
