# Generated by Django 4.2.3 on 2023-07-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
